[package]
name = "OxcideOfOurOwn"
version = "0.1.0"
edition = "2021"

[dependencies]
derive = "1.0.0"
features = "0.10.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
